name: Check pull request

on:
    pull_request:
        branches:
            - master

jobs:
    pr_check:
        name: Pull Request Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python and Rye
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - name: Install Ruff
              run: pip install ruff
            
            - name: Check code
              run: | 
              ruff check .
              ruff fix .

            - name: Auto commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Format code"
                  commit_options: "--no-verify"
                  commit_user_name: "GitHub Actions"
