name: Check pull request

on:
    pull_request:
        branches:
            - master

jobs:
    lint:
        name: Lint code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python and Rye
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install rye
              run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash

            - name: Lint code
              run: rye run lint

    format:
        name: Format code
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python and Rye
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install rye
              run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash

            - name: Format code
              run: rye run format

            - name: Auto commit
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Format code"
                  commit_options: "--no-verify"
                  commit_user_name: "GitHub Actions"
